default: &default
  SECRET_KEY: "N1Z)F@kv,wbbsk2)tWkE:E>MVTqT}c"
  DB_HOST: "localhost"
  DB_USER: "your_username"
  DB_PASSWORD: "your_password"
  DB_NAME: "your_database_name"

development:
  <<: *default
  DB_USER: "root"
  DB_PASSWORD: "Y1j1i1123"
  DB_NAME: "bupt_ims"

production:
  <<: *default
  DB_USER: "prod_user"
  DB_PASSWORD: "prod_password"
  DB_NAME: "prod_database"
